//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFixProyectoWeb.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public int ID_FACTURA { get; set; }
        public string DETALLE { get; set; }
        public double MONTO { get; set; }
        public int ID_USUARIO { get; set; }
        public string METODO_PAGO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
