//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFixProyectoWeb.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_DETALLE
    {
        public int ID_FACTURA_DETALLE { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO { get; set; }
        public Nullable<int> ID_FACTURA_CABECERA { get; set; }
        public string TIPO { get; set; }
        public int CANTIDAD { get; set; }
    
        public virtual FACTURA_CABECERA FACTURA_CABECERA { get; set; }
    }
}
