//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFixProyectoWeb.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_CABECERA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA_CABECERA()
        {
            this.FACTURA_DETALLE = new HashSet<FACTURA_DETALLE>();
        }
    
        public int ID_FACTURA_CABECERA { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string NUMERO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string NOMBRE_MECANICO { get; set; }
        public Nullable<int> ID_PROYECTO { get; set; }
        public bool APROBADO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_DETALLE> FACTURA_DETALLE { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
