//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFixProyectoWeb.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_ESTADOS
    {
        public int ID_HISTORIAL_ESTADO { get; set; }
        public int ID_PROYECTO { get; set; }
        public int ID_ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual ESTADO_PROYECTO ESTADO_PROYECTO { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
