//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFixProyectoWeb.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_ESTADOS
    {
        public int ID_HISTORIAL_ESTADO { get; set; }
        public int ID_PROYECTO { get; set; }
        public int ID_ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual ESTADO_PROYECTO ESTADO_PROYECTO { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
