//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFixProyectoWeb.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMACION_FACTURAS
    {
        public int ID_FACTURA { get; set; }
        public string DETALLE { get; set; }
        public double MONTO { get; set; }
        public int ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
    }
}
