//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFixProyectoWeb.ModelDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class El_Cruce_Entities : DbContext
    {
        public El_Cruce_Entities()
            : base("name=El_Cruce_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIA> CATEGORIA { get; set; }
        public virtual DbSet<COMENTARIOS_PROYECTO> COMENTARIOS_PROYECTO { get; set; }
        public virtual DbSet<COSTO> COSTO { get; set; }
        public virtual DbSet<ESTADO_COSTO> ESTADO_COSTO { get; set; }
        public virtual DbSet<ESTADO_PROYECTO> ESTADO_PROYECTO { get; set; }
        public virtual DbSet<ESTADO_SERVICIO> ESTADO_SERVICIO { get; set; }
        public virtual DbSet<HISTORIAL_ESTADOS> HISTORIAL_ESTADOS { get; set; }
        public virtual DbSet<INVENTARIO> INVENTARIO { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<PROYECTO> PROYECTO { get; set; }
        public virtual DbSet<PROYECTO_PIEZAS> PROYECTO_PIEZAS { get; set; }
        public virtual DbSet<ROLE_USUARIO> ROLE_USUARIO { get; set; }
        public virtual DbSet<SERVICIO> SERVICIO { get; set; }
        public virtual DbSet<TIPO_COSTO> TIPO_COSTO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<VEHICULO> VEHICULO { get; set; }
    }
}
