//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFixProyectoWeb.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_PROYECTO
    {
        public int ID_PRODUCTO_PROYECTO { get; set; }
        public Nullable<int> ID_INVENTARIO { get; set; }
        public int ID_PROYECTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual INVENTARIO INVENTARIO { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
