//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFixProyectoWeb.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROYECTO_PIEZAS
    {
        public int ID_SOLICITUD { get; set; }
        public int ID_PROYECTO { get; set; }
        public int ID_INVENTARIO { get; set; }
        public int ID_COSTO { get; set; }
        public int CANTIDAD { get; set; }
        public int ESTADO { get; set; }
    
        public virtual COSTO COSTO { get; set; }
        public virtual INVENTARIO INVENTARIO { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
