//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFixProyectoWeb.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROYECTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROYECTO()
        {
            this.COMENTARIOS_PROYECTO = new HashSet<COMENTARIOS_PROYECTO>();
            this.FACTURA_CABECERA = new HashSet<FACTURA_CABECERA>();
            this.HISTORIAL_ESTADOS = new HashSet<HISTORIAL_ESTADOS>();
            this.PRODUCTO_PROYECTO = new HashSet<PRODUCTO_PROYECTO>();
            this.PROYECTO_PIEZAS = new HashSet<PROYECTO_PIEZAS>();
            this.SERVICIO_PROYECTO = new HashSet<SERVICIO_PROYECTO>();
        }
    
        public int ID_PROYECTO { get; set; }
        public string ID_VEHICULO { get; set; }
        public int ID_ESTADO_PROYECTO { get; set; }
        public int ID_MECANICO { get; set; }
        public System.DateTime FECHA { get; set; }
        public int ESTADO_FACTURA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMENTARIOS_PROYECTO> COMENTARIOS_PROYECTO { get; set; }
        public virtual ESTADO_PROYECTO ESTADO_PROYECTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_CABECERA> FACTURA_CABECERA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_ESTADOS> HISTORIAL_ESTADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_PROYECTO> PRODUCTO_PROYECTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROYECTO_PIEZAS> PROYECTO_PIEZAS { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO_PROYECTO> SERVICIO_PROYECTO { get; set; }
    }
}
