//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFixProyectoWeb.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESUMEN_USUARIOS
    {
        public int ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string CORREO { get; set; }
        public string CONTRASEÑA { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<bool> ESTADO_CONTRASEÑA { get; set; }
        public int ID_ROLE { get; set; }
        public string ROLE { get; set; }
    }
}
