//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFixProyectoWeb.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIO()
        {
            this.SERVICIO_PROYECTO = new HashSet<SERVICIO_PROYECTO>();
        }
    
        public int ID_SERVICIO { get; set; }
        public string SERVICIO1 { get; set; }
        public string DESCRIPCION { get; set; }
        public double PRECIO { get; set; }
        public int ID_ESTADO { get; set; }
    
        public virtual ESTADO_SERVICIO ESTADO_SERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO_PROYECTO> SERVICIO_PROYECTO { get; set; }
    }
}
