USE EL_CRUCE; 

INSERT INTO ROLE_USUARIO (ROLE) VALUES ('Administrador');
INSERT INTO ROLE_USUARIO (ROLE) VALUES ('Mecanico');
INSERT INTO ROLE_USUARIO (ROLE) VALUES ('Usuario');
GO

INSERT INTO USUARIO (ID_ROLE, NOMBRE, CORREO, CONTRASEÑA, TELEFONO) VALUES (1, 'Cristopher','rufo369@hotmail.es','Cris270497','8748-7314');
GO

SELECT * FROM USUARIO; 