USE EL_CRUCE; 

INSERT INTO ROLE_USUARIO (ROLE) VALUES ('Administrador');
INSERT INTO ROLE_USUARIO (ROLE) VALUES ('Mecanico');
INSERT INTO ROLE_USUARIO (ROLE) VALUES ('Usuario');
GO

INSERT INTO USUARIO (ID_ROLE, NOMBRE, CORREO, CONTRASEÑA, TELEFONO) VALUES (1, 'Cristopher','rufo369@hotmail.es','Cris270497','8748-7314');
GO

CREATE VIEW RESUMEN_USUARIOS AS
	SELECT 
		U.ID_USUARIO,
		U.NOMBRE,
		U.CORREO,
		U.CONTRASEÑA,
		U.TELEFONO,
		U.ESTADO_CONTRASEÑA,
		R.ID_ROLE,
		R.ROLE
	FROM USUARIO U
	INNER JOIN ROLE_USUARIO R ON U.ID_ROLE = R.ID_ROLE; 

SELECT * FROM RESUMEN_USUARIOS;