use EL_CRUCE;
go

-- Para que E.F no muestre error en el modelo, usando en InventarioModel
ALTER TABLE INVENTARIO
ADD NOMBRE VARCHAR(100);

CREATE TABLE FACTURA (
	ID_FACTURA	INT NOT NULL CONSTRAINT PK_FACTURA PRIMARY KEY,
	DETALLE 	VARCHAR(250) NOT NULL, 
	MONTO	 	FLOAT NOT NULL, 
	ID_USUARIO	INT NOT NULL, 
	CONSTRAINT FK_FACTURA_USER FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
) 

ALTER TABLE FACTURA ADD METODO_PAGO VARCHAR(250) NOT NULL;


SELECT * FROM FACTURA; 
SELECT * FROM RESUMEN_USUARIOS; 

INSERT INTO FACTURA (ID_FACTURA, DETALLE, MONTO, ID_USUARIO,METODO_PAGO) VALUES (1,'PROYECTO 1',250,1,'PENDIENTE')
INSERT INTO FACTURA (ID_FACTURA, DETALLE, MONTO, ID_USUARIO,METODO_PAGO) VALUES (2,'PROYECTO 2',250,1,'PENDIENTE')
INSERT INTO FACTURA (ID_FACTURA, DETALLE, MONTO, ID_USUARIO,METODO_PAGO) VALUES (3,'PROYECTO 3',250,1,'PENDIENTE')


ALTER TABLE FACTURA ADD CANCELADO BIT; 

  CREATE OR ALTER VIEW INFORMACION_FACTURAS AS
	SELECT 
		F.ID_FACTURA, 
		F.DETALLE, 
		F.MONTO, 
		F.ID_USUARIO, 
		U.NOMBRE,
		U.TELEFONO,
		F.METODO_PAGO
	FROM FACTURA F
	INNER JOIN USUARIO U ON U.ID_USUARIO = F.ID_USUARIO
GO

CREATE OR ALTER VIEW INFORMACION_FACTURAS_PENDIENTES AS
	SELECT 
		F.ID_FACTURA, 
		F.DETALLE, 
		F.MONTO, 
		F.ID_USUARIO, 
		U.NOMBRE,
		U.TELEFONO,
		F.METODO_PAGO
	FROM FACTURA F
	INNER JOIN USUARIO U ON U.ID_USUARIO = F.ID_USUARIO
	WHERE F.METODO_PAGO = 'PENDIENTE'
GO
  