-- Crear cliente
USE EL_CRUCE;
GO
INSERT INTO USUARIO VALUES(3, 'Yordii', 'yordii@gmail.com', '123', '945-234-892', 1);
INSERT INTO USUARIO VALUES(2, 'Jhenifer', 'jhenifer@gmail.com', '123', '931-500-231', 1);

INSERT INTO VEHICULO VALUES ('PLA-001', 'BMW X5', 'MODELO X', 'CHA 2024', 1, 2);
INSERT INTO VEHICULO VALUES ('CAA-002', 'DXS B5', 'MODELO X2', 'CHA 2023', 1, 2);

INSERT INTO ESTADO_PROYECTO VALUES ('Solicitud a Cliente');
INSERT INTO ESTADO_PROYECTO VALUES ('Inicio del Proyecto');
INSERT INTO ESTADO_PROYECTO VALUES ('Evaluación Inicial');
INSERT INTO ESTADO_PROYECTO VALUES ('Reparación en Proceso');
INSERT INTO ESTADO_PROYECTO VALUES ('Esperando Repuesto');
INSERT INTO ESTADO_PROYECTO VALUES ('Listo para Entrega');
INSERT INTO ESTADO_PROYECTO VALUES ('Entregado');

INSERT INTO ESTADO_SERVICIO VALUES ('Activo');
INSERT INTO ESTADO_SERVICIO VALUES ('Inactivo');

--INSERT INTO SERVICIO VALUES ('Mantenimiento 2000Kg', 'Mantenimiento preventivo para carro nuevo', 100, 1);
--INSERT INTO SERVICIO VALUES ('Servicio test', 'Servicio prueba', 400, 1);
--INSERT INTO PROYECTO VALUES ('PLA-001', 2, 3, GETDATE(), 0);
--INSERT INTO PROYECTO VALUES ('CAA-002', 2, 3, GETDATE(), 0);

--INSERT INTO SERVICIO_PROYECTO VALUES (1, 1, GETDATE());
--INSERT INTO SERVICIO_PROYECTO VALUES (2, 1, GETDATE());
--INSERT INTO SERVICIO_PROYECTO VALUES (1, 2, GETDATE());

INSERT INTO TIPO_COSTO VALUES ('Costo');
INSERT INTO TIPO_COSTO VALUES ('Respuesto');
INSERT INTO TIPO_COSTO VALUES ('Descuento');
