use EL_CRUCE;
go

ALTER TABLE PROYECTO 
ADD FECHA DATETIME;

-- Para que E.F no muestre error en el modelo, usando en InventarioModel
ALTER TABLE INVENTARIO
ADD NOMBRE VARCHAR(100);


CREATE TABLE FACTURA (
	ID_FACTURA	INT NOT NULL CONSTRAINT PK_FACTURA PRIMARY KEY,
	DETALLE 	VARCHAR(250) NOT NULL, 
	MONTO	 	FLOAT NOT NULL, 
	ID_USUARIO	INT NOT NULL, 
	CONSTRAINT FK_FACTURA_USER FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
) 

ALTER TABLE FACTURA ADD METODO_PAGO VARCHAR(250) NOT NULL;
