use EL_CRUCE;
go

ALTER TABLE PROYECTO_PIEZAS
ADD ESTADO INT NOT NULL;

insert into ESTADO_COSTO(DESCRIPCION)
values('Costo')

insert into COSTO([ID_TIPO_COSTO],[ID_ESTADO_COSTO],[MONTO_TOTAL])
 values (1, 1, 5000)

  INSERT INTO INVENTARIO
 VALUES(1, 5, 5000, 10000, 'Aceite')


CREATE TABLE ESTADO_PROYECTO_PIEZAS(
    ID_ESTADO   INT NOT NULL IDENTITY CONSTRAINT PK_ESTADO_PROYECTO_PIEZAS PRIMARY KEY, 
    ESTADO      VARCHAR(20) NOT NULL
)

 insert into ESTADO_PROYECTO_PIEZAS
 VALUES('Rechazado')

 insert into ESTADO_PROYECTO_PIEZAS
 VALUES('Aprobado')

 insert into ESTADO_PROYECTO_PIEZAS
 VALUES('En espera')


DELETE FROM ESTADO_PROYECTO_PIEZAS WHERE ID_ESTADO = 6; 
SELECT * FROM ESTADO_PROYECTO_PIEZAS; 