USE EL_CRUCE; 
GO

SELECT * FROM RESUMEN_USUARIOS;
GO

CREATE OR ALTER VIEW INFORMACION_FACTURAS AS
	SELECT 
		F.ID_FACTURA, 
		F.DETALLE, 
		F.MONTO, 
		F.ID_USUARIO, 
		U.NOMBRE,
		U.TELEFONO
	FROM FACTURA F
	INNER JOIN USUARIO U ON U.ID_USUARIO = F.ID_USUARIO
	WHERE F.METODO_PAGO = 'PENDIENTE'
GO

SELECT * FROM INFORMACION_FACTURAS; 
SELECT * FROM FACTURA;